const FLOAT_SIZE = 4;

const CANVAS_HEIGHT = 960;
const CANVAS_WIDTH = 720;
const BACKGROUND_COLOR_R = 0.6;
const BACKGROUND_COLOR_G = 0.6;
const BACKGROUND_COLOR_B = 0.6;
const BACKGROUND_COLOR_A = 1.0;
const DEFAULT_DEPTH_CLEAR = 1.0;

export {
    CANVAS_WIDTH,
    CANVAS_HEIGHT,
    FLOAT_SIZE,
    BACKGROUND_COLOR_R,
    BACKGROUND_COLOR_G,
    BACKGROUND_COLOR_B,
    BACKGROUND_COLOR_A,
    DEFAULT_DEPTH_CLEAR
};